# Use the official Node.js base image with the latest LTS version
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
