FROM docker.elastic.co/elasticsearch/elasticsearch:8.10.1

COPY ./config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
COPY ./config/log4j2.properties /usr/share/elasticsearch/config/log4j2.properties
