# Generated by Django 5.1.3 on 2025-01-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.FloatField(default=500.0),
        ),
    ]
