# Generated by Django 5.1.3 on 2025-01-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://images-ext-1.discordapp.net/external/FipmzOzQxLkpGNTL0Qs6jhi-4981Q9DL_8D8wQH2WU8/https/res.cloudinary.com/doufu6atn/image/upload/v1726742774/nxdrt0md7buyeghyjyvj.png?format=webp&quality=lossless&width=607&height=607', null=True),
        ),
    ]
