# Generated by Django 5.1.3 on 2025-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='connection_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
