# Generated by Django 5.1.3 on 2025-02-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_connection_id_notification_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
